### ISSUE TITLE
FlatLaf fails with windows installer

### ISSUE THREAD

**Issue by NicoKiaru** [NicoKiaru/ABBA-Python#11]
Java 11

```
Mar 12, 2023 10:58:41 AM com.formdev.flatlaf.util.LoggingFacadeImpl logSevere
SEVERE: null
java.lang.UnsatisfiedLinkError: C:\Users\nicol\AppData\Local\Temp\flatlaf.temp\flatlaf-windows-x86_64-2703454514892000.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at com.formdev.flatlaf.util.NativeLibrary.loadLibraryFromJar(NativeLibrary.java:121)
        at com.formdev.flatlaf.util.NativeLibrary.<init>(NativeLibrary.java:59)
        at com.formdev.flatlaf.ui.FlatNativeLibrary.createNativeLibrary(FlatNativeLibrary.java:76)
        at com.formdev.flatlaf.ui.FlatNativeLibrary.initialize(FlatNativeLibrary.java:63)
        at com.formdev.flatlaf.ui.FlatNativeLibrary.isLoaded(FlatNativeLibrary.java:41)
        at com.formdev.flatlaf.ui.FlatWindowsNativeWindowBorder.getInstance(FlatWindowsNativeWindowBorder.java:96)
        at com.formdev.flatlaf.ui.FlatNativeWindowBorder.initialize(FlatNativeWindowBorder.java:276)
        at com.formdev.flatlaf.ui.FlatNativeWindowBorder.isSupported(FlatNativeWindowBorder.java:70)
        at com.formdev.flatlaf.ui.FlatNativeWindowBorder.install(FlatNativeWindowBorder.java:78)
        at com.formdev.flatlaf.ui.FlatRootPaneUI.installNativeWindowBorder(FlatRootPaneUI.java:234)
        at com.formdev.flatlaf.ui.FlatRootPaneUI.installUI(FlatRootPaneUI.java:108)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
        at java.desktop/javax.swing.JRootPane.setUI(JRootPane.java:449)
        at java.desktop/javax.swing.JRootPane.updateUI(JRootPane.java:459)
        at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1363)
        at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
        at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1354)
        at com.formdev.flatlaf.FlatLaf.updateUI(FlatLaf.java:997)
        at org.scijava.ui.swing.laf.SwingLookAndFeelService.setLookAndFeel(SwingLookAndFeelService.java:144)
        at org.scijava.ui.swing.laf.SwingLookAndFeelService.initLookAndFeel(SwingLookAndFeelService.java:91)
        at net.imagej.legacy.IJ1Helper.setVisible(IJ1Helper.java:324)
        at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:132)
        at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:166)
        at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:151)
```

**Comment by NicoKiaru** [comment]
Fixed by reverting to Java 8...
